### ISSUE TITLE
RobotisController.h is including header files from dynamixel_sdk

### ISSUE THREAD

**Issue by ghost** [ROBOTIS-GIT/ROBOTIS-Framework#12]
Following are code snippets from the file RobotisController.h of the ROBOTIS-Framework repository.
The system that I am working on is an Ubuntu 14.04, shouldn't the header files be from dynamixel_sdk_linux? And the snippets show comments saying TODO: TEMPORARY CODE. Does this need to be updated?

```
// TODO: TEMPORARY CODE !!
#include "dynamixel_sdk/GroupBulkRead.h"
#include "dynamixel_sdk/GroupSyncWrite.h"
```

```
// TODO: TEMPORARY CODE !!
    std::map<std::string, GroupBulkRead *>  port_to_bulk_read;
    std::map<std::string, GroupSyncWrite *> port_to_sync_write_position;
    std::map<std::string, GroupSyncWrite *> port_to_sync_write_velocity;
    std::map<std::string, GroupSyncWrite *> port_to_sync_write_torque;
```

**Comment by kysel** [comment]
No it shouldn't, if you look into dynamixel_sdk_linux folder you'll find only `PortHandlerLinux.cpp`. And that's only one difference between linux and windows implementation (protocol is still the same, port handling not).
And for the second question: yes, it should be rewrite to properly support MX-28 actuator.

**Comment by ROBOTIS-zerom** [comment]
See the "develop" branch..

**Comment by ghost** [comment]
I'm sorry, I didn't properly track the header files. After going through the code for RobotisController.cpp again, I have figured out that my error was coming from the pthread_create() function, giving an error value of 1 (EPERM error). The function is on the line 481 of RoboticController.h and I am getting the error message as given on line 482. 
Error Message:

```
[ INFO] [1464938807.597236403]: error: 1
[ERROR] [1464938807.597311436]: timer thread create fail!!
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
```

I would be truly grateful if you could help me solve this problem because a thread scheduling error is  not something that I know how to solve on my own. Also, I apologize if this is not the correct place for asking doubts.

**Comment by kysel** [comment]
Scheduling thread with the SCHED_RR scheduling policy require root permission. Just launch the app as root.
Ore use another scheduling policy.. (change [this line](https://github.com/ROBOTIS-GIT/ROBOTIS-Framework/blob/master/robotis_controller/src/robotis_controller/RobotisController.cpp#L467))

**Comment by ghost** [comment]
Thank you very much for all your help. You were right, I should have run the code as user, instead of using sudo only for the roslaunch. Successfully got the motor running using the gui. 
Erm, could you suggest where I should post doubts if I should have some in the near future, I don't think the 'Issues' page is the right place.

Thanks once again!

**Comment by kysel** [comment]
Maybe you should try to use some [stackexchange](http://stackexchange.com) site eg. [robotics](http://robotics.stackexchange.com). Properly tagged question is often answered within  days.
