### ISSUE TITLE
Inverse Kinematics Algorithm

### ISSUE THREAD

**Issue by ghost** [ROBOTIS-GIT/ROBOTIS-Framework#18]
Will the inverse kinematics algorithm used for the Robotis Manipulator be applicable for a redundant manipulator (7 motors)? And if so, what all changes will I need to make in the code? Is it just sufficient to change the values at the start of the ManipulatorKinematicsDynamics.cpp file or are there other changes to make as well?

**Comment by s-changhyun** [comment]
You do not have to change anything. 
Please refer the THORMANG3_MANIPULATION_MODULE (https://github.com/ROBOTIS-GIT/ROBOTIS-THORMANG-MPC/tree/master/thormang3_manipulation_module).
