### ISSUE TITLE
fatal: repository 'https://github.com/ROBOTIS-GIT/ROBOTIS-Frmaeowrk-msgs.git/' not found

### ISSUE THREAD

**Issue by amirhm64** [ROBOTIS-GIT/ROBOTIS-Framework#41]
I am trying to install Manipulator-h ROS packages. and it's not possible. ROBOTIS-Frmaeowrk-msgs.git is not accessible

**Comment by s-changhyun** [comment]
I think that you had a miss typing. 

ROBOTIS-Frmaeowrk-msgs.git ->  ROBOTIS-Framework-msgs.git

**Comment by amirhm64** [comment]
I copied from the tutorial:
https://github.com/ROBOTIS-GIT/ROBOTIS-Documents/wiki/ROBOTIS-Framework

**Comment by s-changhyun** [comment]
I modified tutorial

**Comment by amirhm64** [comment]
Thanks
